# Change these first
owner: abimanyu # Your GitHub organization or username, where this repository lives
repo: Kalbarnetworks # The name of this repository

sites:
  - name: Kalbar Prov
    url: https://www.kalbarprov.go.id
  - name: Badan Penghubung
    url: https://penghubung.kalbarprov.go.id
  - name: BALITBANG
    url: https://litbang.kalbarprov.go.id
  - name: BAPENDA
    url: https://bapenda.kalbarprov.go.id

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /Kalbarnetworks
  logoUrl: https://upload.wikimedia.org/wikipedia/commons/5/5d/Coat_of_arms_of_West_Kalimantan.svg
  name: Status Web Pemerintahan Kalimantan Barat - Kalbarnetworks
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /Kalbarnetworks
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  activeIncidents: Kendala Aktif
  allSystemsOperational: Semua sistem beroperasi
  incidentReport: "Laporan kendala #$NUMBER →"
  activeIncidentSummary: Dibuka pada $DATE dengan $POSTS postingan
  incidentTitle: Detail Kendala $NUMBER
  incidentDetails: Detail Kendala
  incidentFixed: Diperbaiki
  incidentOngoing: Sedang berlangsung
  incidentOpenedAt: Dibuka pada
  incidentClosedAt: Ditutup pada
  incidentSubscribe: Berlangganan Pembaruan
  incidentViewOnGitHub: Lihat di GitHub
  incidentCommentSummary: Diposting pada $DATE oleh $AUTHOR
  incidentBack: ← Kembali ke semua kendala
  pastIncidents: Kendala Masa Lalu
  pastIncidentsResolved: Diselesaikan dalam $MINUTES menit dengan $POSTS postingan
  liveStatus: Live Status
  overallUptime: Uptime keseluruhan $UPTIME%
  overallUptimeTitle: Uptime keseluruhan
  averageResponseTime: Waktu respons rata-rata $TIMEms
  averageResponseTimeTitle: Respon rata-rata
  sevelDayResponseTime: Waktu respons 7 hari
  responseTimeMs: Waktu respons (ms)
  up: Aktif
  down: Non-aktif
  ms: ms
  loading: Loading
  navGitHub: GitHub
  footer: Halaman ini [open source]($REPO), dikembangkan oleh [Abimanyu Yusuf](https://github.com/abimanyu) dengan menggunakan [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Batas tarif terlampaui
  rateLimitExceededIntro: Anda telah melebihi jumlah permintaan yang dapat Anda lakukan dalam satu jam, jadi Anda harus menunggu sebelum mengakses situs web ini lagi. Sebagai alternatif, Anda dapat menambahkan Token Akses Pribadi GitHub untuk terus menggunakan situs web ini.
  rateLimitExceededWhatDoesErrorMean: Apa arti kesalahan ini?
  rateLimitExceededErrorMeaning: Situs web ini menggunakan API GitHub untuk mengakses data waktu nyata tentang status situs web kami. Secara default, GitHub mengizinkan setiap alamat IP 60 permintaan per jam, yang telah Anda gunakan.
  rateLimitExceededErrorHowCanFix: Bagaimana cara memperbaikinya?
  rateLimitExceededErrorFix: Anda dapat menunggu satu jam lagi dan batas alamat IP Anda akan dipulihkan. Sebagai alternatif, Anda dapat menambahkan Token Akses Pribadi GitHub Anda, yang memberi Anda 5.000 permintaan tambahan per jam.
  rateLimitExceededGeneratePAT: Pelajari cara membuat Token Akses Pribadi
  rateLimitExceededHasSet: Anda memiliki set token akses pribadi.
  rateLimitExceededRemoveToken: Hapus token
  rateLimitExceededGitHubPAT: Token Akses Pribadi GitHub
  rateLimitExceededCopyPastePAT: Salin dan tempel token Anda
  rateLimitExceededSaveToken: Simpan token
  errorTitle: Terjadi kesalahan
  errorIntro: Terjadi kesalahan saat mencoba mendapatkan detail status terbaru.
  errorText: Anda dapat mencoba lagi dalam beberapa saat.
  errorHome: Buka beranda

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
